name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort mypy pylint

    - name: Format check with Black
      run: black --check --diff src/ tests/

    - name: Import sorting check with isort
      run: isort --check-only --diff src/ tests/

    - name: Type checking with mypy
      run: mypy src/ --ignore-missing-imports

    - name: Lint with pylint
      run: pylint src/ --output-format=text --reports=no --score=no

    - name: Run tests with coverage
      run: |
        pip install pytest-cov
        pytest tests/ --cov=src --cov-report=term-missing --cov-fail-under=80

  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install pip-audit
      run: pip install pip-audit

    - name: Audit dependencies
      run: |
        pip install -r requirements.txt
        pip-audit

    - name: Check for outdated packages
      run: |
        pip install pip-check
        pip-check
